### ISSUE TITLE
Problems with "hide on mobile/desktop" options

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#100]
Some time ago we discussed how do the "hide on mobile/desktop" options work. The discussion is here:
https://github.com/EDMdesigner/editor-issues/issues/66

But now my clients have some more questions about it. Please see below:

If we look at the table of compatibility of EDM editor, we can see gmail app in MOBILE CLIENTS and gmail in WEB-BASED CLIENTS:
https://edmdesigner.com/compatibility/
This makes us feel that the "hide on mobile/desktop" options must work correctly in gmail. But if we look at the screenshot in attachment (GMAIL.COM) we can see that it doesn't. There is a difference between "doesn't work" and "works incorrectly". In our case it works incorrectly because:
1) the box with options
Hide on mobile: ON
Hide on desktop: OFF
doesn't display in gmail app on mobile
2) the box with options
Hide on mobile: ON
Hide on desktop: ON
displays in gmail app on mobile

So it looks like for the first one box gmail app is mobile and for the second it is not. It looks like a bug.

The second case is about mail.ru app. Table of compatibility doesn't contain it. So it would be ok if all the boxes were displayed in mail.ru app independently of "hide on mobile/desktop" options. But the boxes are diplaying by some strange rules. Is it ok? Does it work like it should?

![gmail com](https://user-images.githubusercontent.com/17157918/32004890-2d258294-b9a3-11e7-9971-b33ec52177ea.jpg)

![mail ru](https://user-images.githubusercontent.com/17157918/32004882-25952e6c-b9a3-11e7-9f45-5fadbafb44a9.jpg)

**Comment by smiska** [comment]
Hi,
"Hide on mobile: ON" means it would not show up on mobile devices while "Hide on desktop: ON" means that the element will not show on desktop. However, if you toggle both of the switches " ON", it can cause  unexpected behavior in email clients, like you've seen in Gmail and Mail.ru app. 

You should not define both of the switches "ON", because as the underlying code works the two definition cross each other. Hiding a single element both on desktop and mobile doesn't really make sense. A typical use case would be to define a similar functionality twice: one for mobile clients and you set "Hide on desktop: ON"  on it and one for desktop and set "Hide on mobile: ON" that element.

Why Mail.ru mobile app hides elements when "Hide on desktop: ON" is switched needs investigation, but it's good to know that this can happen. At the moment, I would suggest not to use this functionality or use it with special caution in cases, where the email campaigns audience are very likely to use Mail.ru mobile app.

**Comment by agnieszkakowalska** [comment]
Please investigate why Mail.ru mobile app hides elements when "Hide on desktop: ON" and fix it. We have a huge Russian market, and more than 60% of our customers' subscribers in Russia use mail.ru. This is why it is very important for us.

**Comment by smiska** [comment]
We could investigate the problem and found that it only affects the Android Mail.ru app, even with updated Android and latest app version (it displays correctly on iOS). 

The reason is that we hide the elements with inline styles and switch it to display with through media query from the `head` element. When "Hide on desktop: ON" is set, there would be media query in the `style` tag switching the element to display on mobiles, but since it's not supported in the Android Mail.ru app this switch does not apply. Unfortunately this way we can't support the Android app, while the feature will work on iOS.

**Comment by agnieszkakowalska** [comment]
Thank you for your answer @smiska
