### ISSUE TITLE
Saves changes temporarily

### ISSUE THREAD

**Issue by Silassiai** [EDMdesigner/editor-issues#102]
Hi,

When a customer of us saves the template, the template will be change temporarily.
If we go out of the editor and reopen the template again we will see the correct changes.
But if we wait a couple of minutes and open the template in the editor again the changes are back to an earlyer version.

Any idea how this is posible?

[5a4c9816a373564235c19456.txt](https://github.com/EDMdesigner/editor-issues/files/1600480/5a4c9816a373564235c19456.txt)

**Comment by smiska** [comment]
Hi @Silassiai ,

By default, the editor has an [autosave functionality](http://apidocs.edmdesigner.com/#editor-iframe).
Is it possible that this was disabled for example because you have a custom save button configured in the UI? 

The other possible cause can be some sort of network problem. Could you send an email with the credentials of a test account to support@edmdesigner.com  ? Then I could take a look if I can find something wrong there.
