### ISSUE TITLE
Image Group problem in r20160219

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#12]
Dear Gyula,

This was the issue reported to you by email before, we copy it to here so that you can follow more easily as this problem still occurs in r20160219

1) Created 3 image blocks
2) Removed 2nd image
3) Re-insert 2nd image, the 2nd image disappeared in right hand side

![2016-02-22_15-53-56](https://cloud.githubusercontent.com/assets/5524183/13212541/f50b08c8-d97c-11e5-8e5d-ec6db36c3808.jpg)

Thanks.

**Comment by gyulanemeth** [comment]
Thank you for opening this issue, we will investigate it in our next spring starting on Wednesday.

**Comment by iamgaborgithub** [comment]
Dear confettidc,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
