### ISSUE TITLE
Border widths feature

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#13]
Hi, I was already writing you about this, but would like to post it here for better tracking.

Would you be able to add numbers for border’s width, the same as in padding and margin? Our client suggested that it would be useful to quickly see what’s the width without clicking on each border separately.
![a](https://cloud.githubusercontent.com/assets/17157918/13420645/49c94184-df88-11e5-8d07-00d12a6018d0.png)

**Comment by agnieszkakowalska** [comment]
Hi, I am wondering if there are any chances to implement this feature?

**Comment by gyulanemeth** [comment]
Hello, at the moment I'm not sure that we'll have enough time to implement this feature. Also, if we implemented a new type of the border toolbox, that would be totally different. We got many feedbacks that it's not intuitive enough.

**Comment by agnieszkakowalska** [comment]
OK I understand, thank you

**Comment by gyulanemeth** [comment]
Are you interested about our thoughts of a new button toolbox? It would be simpler and easier to use. We can talk about it on skype some time.

**Comment by iamgaborgithub** [comment]
Dear agnieszkakowalska,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
