### ISSUE TITLE
H1 element formatting issue in Firefox

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#15]
If you add H1 element in Firefox, double click and start to write, the formatting disappears.

**Comment by gyulanemeth** [comment]
Thank you for creating a github ticket, we will reinvestigate the issue and hopefully we will find a fix soon.

**Comment by iamgaborgithub** [comment]
Dear agnieszkakowalska,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
