### ISSUE TITLE
Social Follow Element on Mobile

### ISSUE THREAD

**Issue by GVLien** [EDMdesigner/editor-issues#22]
The social follow element cannot be edited/re-ordered on mobile. Therefore the logos are stacked on top of each other in mobile views. 

![social follow](https://cloud.githubusercontent.com/assets/18006428/13951101/b54de960-f026-11e5-9729-d172b2d03043.jpg)

**Comment by arnolduis** [comment]
Thank you for reporting this issue! We will investigate and fix it soon.

**Comment by GVSupport** [comment]
Hi there, any news on this issue?

**Comment by iamgaborgithub** [comment]
Dear GVSupport,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
