### ISSUE TITLE
502 error with json/project/setProject endpoint

### ISSUE THREAD

**Issue by vcampitelli** [EDMdesigner/editor-issues#23]
Hi there!

I've been trying to use the `json/project/setProject` endpoint but I keep getting _502 Bad Gateway_.

The payload is about 44kB.

Can you help me?

Thank you,

**Comment by ghost** [comment]
Thank you for reporting this issue! We will investigate and fix it soon.

**Comment by arnolduis** [comment]
Can you send us the json you have used, and the request headers please?

**Comment by vcampitelli** [comment]
Sure!

Request headers:

```
POST /json/project/setProject?user=admin&token=c6d3237e1d173a88c0e1b9205e630c1a HTTP/1.1
Host: api-a.edmdesigner.com
Accept: */*
Content-Length: 44796
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue
```

Payload: [payload.txt](https://github.com/EDMdesigner/editor-issues/files/199766/payload.txt)

Response:
`502 Bad Gateway
nginx/1.4.6 (Ubuntu)`

Thank you!

**Comment by iamgaborgithub** [comment]
Dear Vinícius,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
