### ISSUE TITLE
Bug on link generate

### ISSUE THREAD

**Issue by m33ch** [EDMdesigner/editor-issues#24]
Some link like this one is "broked" from edm

https://h22166.www2.hp.com/event/eventpage.aspx?eventid=OAAwADUANAAyAA==&cc=it&lang=it

if make a button with this link, in the generated html code it became like this:

https://h22166.www2.hp.com/event/eventpage.aspx?eventid=OAAwADUANAAyAA&cc=it%E2%9F%A8\

if i make a link with the same url in a text area, in the resulting html code it became like this:

https://h22166.www2.hp.com/event/eventpage.aspx?eventid=OAAwADUANAAyAA&cc=it&lang=it\

So the links result broken

**Comment by balintsoos** [comment]
Thank you for reporting this issue! We will investigate and fix it soon.

**Comment by iamgaborgithub** [comment]
Dear Alessandro,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
