### ISSUE TITLE
Missing link on image group

### ISSUE THREAD

**Issue by m33ch** [EDMdesigner/editor-issues#25]
Hi all,

on image group element missing attach link functionality on the images.

Thanks

**Comment by ghost** [comment]
Thank you for reporting this issue, we will investigate and fix it soon.

**Comment by balintsoos** [comment]
Thanks for the report! We were thinking about to add all image element options to the image group as well but it may take some time, because it's a new feature.

**Comment by iamgaborgithub** [comment]
Dear Alessandro,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
