### ISSUE TITLE
Preview Text

### ISSUE THREAD

**Issue by leggomuhgreggo** [EDMdesigner/editor-issues#27]
Is there a way to insert preview text?

[reference](https://litmus.com/blog/the-ultimate-guide-to-preview-text-support)

**Comment by leggomuhgreggo** [comment]
Hey so I tried using a box element and hiding on both mobile and desktop, but the hide mobile doesn't work for gmail/android

Looked into a font size 0 option, but looks like there's a min of 5px

Right now I'm adding text that's the same color as the bg, but it'd be nice if it werent selectable.

Thanks!

**Comment by leggomuhgreggo** [comment]
Wanted to follow up on this.

**Comment by rolficak** [comment]
This is not available in the editor right now. I created a ticket in our backlog, and if others mention it it will get higher priority. Thanks for the thoughts!

**Comment by leggomuhgreggo** [comment]
Would you consider adding the ability to reduce the font size to zero, as a short term workaround?

**Comment by rolficak** [comment]
I don't think that it would work in most email clients. @ughoo can answer this.

**Comment by leggomuhgreggo** [comment]
Hey @rolficak and @ughoo, I looked into this more and I can actually just throw a transparent 1px x 1px image as the first element and the alt text will work. 

If you guys were thinking about implementing this, this might be the preferred method. Could probably even use an empty dataURI as the img src, and the alt text could maybe be a string from an input in the default tab of the editor sidebar? Actually dataURI might mess with peoples' tracking implementations.

Anyway I think I have my workaround. Thanks for your consideration.

**Comment by ughoo** [comment]
Hey @leggomuhgreggo to hide someting on all platforms, that should be spamy technique...lots of services will deny or reduce your reputation as a sender. Also to set text to same color as its background is a technique i recommend to avoid, because in the past these tricks were used to mislead users.....

You can reduce the font-size in the html by hand, but some of the clients will ignore or overrides it if its smaller than 8-9-10px - its different on devices/softwares. So we not supports this way.

The empty img is sounds as a great workaround, but I'm not sure that safe to use on all the email clients which we support. Let's see! Thanks!
