### ISSUE TITLE
Social Follow URL/mailto field contents/guidance not updating when follow type is changed

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#30]
After adding a 'Social Follow' Element to a design, when modifying the element, if the 'add another' button is used to add a third type and then the type is changed (e.g. from LinkedIn to Email), the 'Email Address/URL' field content does not update to reflect the new type of follow selected.

The field title changes (e.g. to Email Address) and the box is highlighted red, but the content remains (e.g. saying 'https://linkedin.com).

![edmsupport2](https://cloud.githubusercontent.com/assets/18616807/14845927/0e973d3e-0c59-11e6-9d0e-e9a92ae157f0.JPG)

If another element is selected and the social follow is re-selected, then the content is correctly updated.

I have recreated this issue in our own implementation of EDM and on the 'Try it now' template on edmdesigner.com using IE11, Edge and Chrome (all on Windows 10).

**Comment by gyulanemeth** [comment]
Hello,

we have some general problem with updating some state variables of certain elements. We are investigating it, hopefully we will be able to provide a solution soon.

**Comment by bretkempler** [comment]
Same issue here.  Seeing when set to email and switching, mailto: remains.
Also see switching social keeps the old social url.

Informed my customer that you have to put the complete url anyway...  like follow us and just go to FB main page wouldn't be enough.

**Comment by iamgaborgithub** [comment]
Dear GVSupport,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
