### ISSUE TITLE
Add more font family selection for other language characters

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#35]
Dear Support,

Can you provide more font family selections for other language characters (e.g. Chinese) so that we can made the eDM text more beautiful?

The existing font families seems too few for us, thanks.
![2016-05-09_12-19-20](https://cloud.githubusercontent.com/assets/5524183/15103650/4cef181e-15e0-11e6-957b-44b4815db4cb.png)

**Comment by gyulanemeth** [comment]
Can you recommend some font families?

**Comment by confettidc** [comment]
You may refer to below fonts, thanks.

[fonts.zip](https://github.com/EDMdesigner/editor-issues/files/256180/fonts.zip)

**Comment by smiska** [comment]
Custom font support settings was added to the dashboard. Please check out if it's what you have been looking for. [Screenshot on the new settings to find it easier.](https://user-images.githubusercontent.com/16736043/28075817-ecc18174-665c-11e7-9fe4-deeea0c206c5.png)

**Comment by iamgaborgithub** [comment]
Dear confettidc,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
