### ISSUE TITLE
Client has problems with text bar

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/editor-issues#37]
A client of ours (working on safari, Apple) has an issue where the pop up text menu bar is constantly blocking the text and not scrolling up. Any way to fix this without having to change browser?

Thanx,

Richard

**Comment by gyulanemeth** [comment]
Hello,

can you please attach some screenshots?

**Comment by iamgaborgithub** [comment]
Dear Richard,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
