### ISSUE TITLE
Adding URL Link Using Microsoft Edge Is Not Working

### ISSUE THREAD

**Issue by GVThorne** [EDMdesigner/editor-issues#41]
Hi,

Using Microsoft Edge, when clicking on the 'Link' button within the Text Editor, I am unable to click the 'Ok' button to add in my URL link. The link dialog box appears after I have selected the 'Link' button but once I have entered my URL data, clicking 'OK' does nothing.

This only happens when using Microsoft Edge and the following error message occurs within the browser console each time the 'OK' button is clicked:

**_Unable to get property 'collapsed' of undefined or null reference_**

Thanks

**Comment by gyulanemeth** [comment]
Were there any more errors? If yes, can you copy them here?

**Comment by GVThorne** [comment]
No, that was the only error message reported. However the error message is not displayed to the user directly but is found within the Microsoft Edge browser console as below:
![image](https://cloud.githubusercontent.com/assets/19688100/15958054/1fd7313a-2eeb-11e6-8b86-1c69fa6bdc48.png)

**Comment by iamgaborgithub** [comment]
Dear GVThorne,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
