### ISSUE TITLE
Image won't change when upload an image with same name

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#45]
Project ID: 576ce0b4373b92c9425d5e04
Editor version: r20160219

Please find below video for the error, thanks.
[2016-06-24_17-29-00.zip](https://github.com/EDMdesigner/editor-issues/files/331539/2016-06-24_17-29-00.zip)

**Comment by gyulanemeth** [comment]
I'm guessing the url of the image is the same so the browser won't try to download it again. I'm guessing that if you refresh the editor, it will show the good image. Am I correct?

**Comment by confettidc** [comment]
Yes, but is that anyway to force the browser to re-download the image?

Thanks.

**Comment by iamgaborgithub** [comment]
Dear confettidc,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
