### ISSUE TITLE
Image border bug in editor

### ISSUE THREAD

**Issue by ughoo** [EDMdesigner/editor-issues#47]
When user applies border on image, the width of the border is decreased with the value of the border twice. If you increase the border value a gap will appear on the both sides...

**Comment by iamgaborgithub** [comment]
Dear ughoo,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
