### ISSUE TITLE
Responsive Editor does not work properly on Apple (Chrome en Safari)

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/editor-issues#49]
By a customer their is a problem with the responsive editor when they use it on an Apple iOS (Finder/OS version 10.6.8).

Both in Chrome (v 49.0.263.112) and Safari (v 5.1.10) when they (double) click in a text box the text edit menu is not popping up. So they can't change the text and the format of the text. Can you please look to this issue and solve this.

![da3856fed9ca408a90ba532b293f9ca3](https://cloud.githubusercontent.com/assets/16222817/16556910/faf23356-41dc-11e6-805b-407bd314f893.png)

**Comment by iamgaborgithub** [comment]
Dear Mailcamp,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
