### ISSUE TITLE
LIVE API: Color picker not working

### ISSUE THREAD

**Issue by rolficak** [EDMdesigner/editor-issues#52]
Windows 7  Chrome  Version 51.0.2704.103 m (64-bit)
Cannot pick color, only the input field is working.

**Comment by iamgaborgithub** [comment]
Dear rolficak ;) ,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
