### ISSUE TITLE
Social Element Enhancement - YouTube

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#54]
Could you please make the YouTube Icon available in the Social elements?

**Comment by iamgaborgithub** [comment]
Dear GVSupport,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
