### ISSUE TITLE
Can't add link on IE

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/editor-issues#55]
email: jcbalcom@gmail.com 
time: Fri Aug 26 2016 15:04:29 GMT+0000 (UTC) 
user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393 
browser language: en-US 
platform: Win32 
details: Windows NT 10.0; Win64; x64 
OS language: No information 

message: 

I can't add a URL link to text. When I press OK nothing happens. I have to cancel to leave the link dialog.

**Comment by Mailcamp** [comment]
our customer does not have this problem in explorer.
She have it in edge only.

**Comment by iamgaborgithub** [comment]
Dear gyulanameth ;),

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
