### ISSUE TITLE
Proposal: Add "margin: auto" to "body" in the editor iframe

### ISSUE THREAD

**Issue by leggomuhgreggo** [EDMdesigner/editor-issues#59]
Kind of a minor thing, and there are workarounds, but the default width of the iframe appears to be `1200px`, which exceeds the width of the interface of `995px`. Right now I'm containing the iframe with, using styles, which is fine, but it occurs to me that adding `margin-left: auto; margin-right: auto;` to the `body` of the editor `iframe` would be sensible, so that the interface is centered if there's any excess.

Thank you for your consideration.

**Comment by iamgaborgithub** [comment]
Dear Greg,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
