### ISSUE TITLE
55084S: Mailshot not rendering correclty in Outlook 2007

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#60]
One of our clients is seeing a strange rendering issue in outlook 2007 which isn't present in newer versions or other mail clients.

The correctly rendering design looks like this;

![pasted image at 2016_10_06 04_58 pm](https://cloud.githubusercontent.com/assets/18616807/19160933/be43ca8a-8be9-11e6-90ea-d19e34cff036.png)

the outlook 2007 version looks like this;

![pasted image at 2016_10_06 04_58 pm 1](https://cloud.githubusercontent.com/assets/18616807/19160967/de056fae-8be9-11e6-8983-afb2424062aa.png)

I haven't been able to find an obvious cause of this issue.

Thanks

**Comment by rolficak** [comment]
@GVSupport Please aslo send us the projectId, JSON and exported HTML. Than @ughoo will look into this.

**Comment by gyulanemeth** [comment]
[emailSource - 54834S.txt](https://github.com/EDMdesigner/editor-issues/files/541548/emailSource.-.54834S.txt)

I've got this html in email.

**Comment by ughoo** [comment]
the attached source is a totally different template...we need the original which is on the screenshots.

**Comment by ughoo** [comment]
@GVsupport please attach the related html to start the investigation. Thanks.

**Comment by iamgaborgithub** [comment]
Dear GVSupport,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
