### ISSUE TITLE
Feature Req: Editable Default Line Height Settings

### ISSUE THREAD

**Issue by leggomuhgreggo** [EDMdesigner/editor-issues#61]
The current default is ~1em, which means that anytime someone's starting a new template, it's an adjustment that has to be made. It'd be great to be able to define that globally somewhere. Thanks!

**Comment by iamgaborgithub** [comment]
Dear Greg,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
