### ISSUE TITLE
Alt text bug

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/editor-issues#63]
Hi Gyula,
 
We discovered a bug in EDMdesigner.
Is a customer puts an ALT tekst llike; Castelijn & Beerens Bravo 15,6" the editor doesn’t show the element and even crashes the browser. Please check attachment.
So if people use " for pointing out inches it goes wrong.
 
Please let me know if thiscan be fixed bij addslashes or whatever.
 
 
 
Voor een snellere afhandeling van support zaken verwijs ik graag naar support@mailcamp.nl
 
Met vriendelijke groet,
Jasper Reijn

**Comment by iamgaborgithub** [comment]
Dear gyulanameth ;),

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
